apiVersion: v1
kind: Service
metadata:
  name: {{ include "image-processing.fullname" . }}
  labels:
    {{- include "image-processing.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "image-processing.selectorLabels" . | nindent 4 }}
