apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.pvc.storageClassName }}
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: {{ .Values.efs.fileSystemId }}
  directoryPerms: "755"
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: Immediate
