name: Image processing
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  call-cicd:
    uses: ./.github/workflows/cicd.yaml
    with:
      ecr_repository: "image-processing-app-ecr-prod"
      helm_chart_dir: "helm/image-processing"
      aws_region: "us-west-2"
      image_name: "image-processing-app-prod"
      chart_tag_key: "tag"
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_PRODUCTION }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_PRODUCTION }}
